spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.DB_URL}
    username: ${secrets.DB_USER}
    password: ${secrets.DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method

cloud:
  aws:
    s3:
      bucket: trippiece-bucket
      path:
        trippiece : trippieces
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${secrets.AWS_ACCESS_KEY_ID}
      secretKey: ${secrets.AWS_SECRET_ACCESS_KEY}

jwt:
  secret: ${secrets.JWT_KEY}
  accessTokenValidity: 7200000 # 2 hour
  refreshTokenValidity: 604800000 # 1 week