profiles:
  default: local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trippiece
    username: root
    password: 3911
    include:
      - local


    jpa:
      database: mysql
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          jdbc:
            time_zone: Asia/Seoul
      hibernate:
        ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
